CREATE TABLE TB_EMPRESAS_TCC (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	ATIVO TINYINT(1) DEFAULT 1,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TB_USUARIOS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    ATIVO TINYINT(1) DEFAULT 1 NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_ID_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID)
);


CREATE TABLE TB_CLIENTES_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255),
    TIPO_PESSOA VARCHAR(1),
    DOCUMENTO VARCHAR(20),
    DATA_NASCIMENTO DATE,
    TELEFONE_RESPONSAVEL VARCHAR(20) NOT NULL,
    TELEFONE_COMERCIAL VARCHAR(20),
    TELEFONE_OUTROS VARCHAR(20),
    ENREDECO_RESPONSAVEL VARCHAR(255) NOT NULL,
    ENDERECO_COMERCIAL VARCHAR(255),
    ENDERECO_OUTROS VARCHAR(255),
    ATIVO TINYINT(1) DEFAULT 1 NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_ID_EMPRESA_TB_CLIENTES_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_CLIENTES_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_FORNECEDORES_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    FANTASIA VARCHAR(150) NOT NULL,
    RAZAOSOCIAL VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    TPPESSOA VARCHAR(1) NOT NULL,
    DOCUMENTO VARCHAR(20),
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(255),
    ATIVO TINYINT(1) DEFAULT 1 NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_ID_EMPRESA_TB_FORNECEDORES_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_FORNECEDORES_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_FUNCIONARIOS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TPPESSOA VARCHAR(1) NOT NULL,
    DOCUMENTO VARCHAR(20) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    ATIVO TINYINT(1) DEFAULT 1 NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_ID_EMPRESA_TB_FUNCIONARIO_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_FUNCIONARIO_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_ESTADOS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TB_CIDADES_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ESTADO INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_ESTADO_TB_CIDADES_TCC FOREIGN KEY (ID_ESTADO) REFERENCES TB_ESTADOS_TCC (ID)
);

CREATE TABLE TB_CATEGORIAS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_CATEGORIAS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_CATEGORIAS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_MARCAS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_FORNECEDOR_TB_MARCAS_TCC FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDORES_TCC (ID),
    CONSTRAINT FK_ID_EMPRESA_TB_MARCAS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MARCAS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_LINHAS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ID_MARCA INT NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_MARCA_TB_LINHAS_TCC FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCAS_TCC (ID),
    CONSTRAINT FK_ID_EMPRESA_TB_LINHAS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_LINHAS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_PRODUTOS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(1000) NOT NULL,
	IMAGES VARCHAR(1000) NOT NULL,
	SLUG VARCHAR(255) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    ESTOQUE INT NOT NULL,
    ESTOQUEMINIMO INT NOT NULL,
    ESTOQUEMAXIMO INT NOT NULL,
    PRECOCUSTO INT(10, 2) NOT NULL,
    PRECOVENDA INT(10, 2) NOT NULL,
    STATUS TINYINT(1) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_LINHA INT NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_CATEGORIA_TB_PRODUTOS_TCC FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIAS_TCC (ID),
    CONSTRAINT FK_ID_LINHA_TB_PRODUTOS_TCC FOREIGN KEY (ID_LINHA) REFERENCES TB_LINHAS_TCC (ID),
    CONSTRAINT FK_ID_MARCA_TB_PRODUTOS_TCC FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCAS_TCC (ID),
    CONSTRAINT FK_ID_EMPRESA_TB_PRODUTOS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
	CONSTRAINT FK_ID_FORNECEDOR_TB_PRODUTOS_TCC FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDORES_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_PRODUTOS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_COND_PAGAMENTOS_TCC (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TB_FRM_PAGAMENTOS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CONDICAO INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_CONDICAO_TB_FRM_PAGAMENTOS_TCC FOREIGN KEY (ID_CONDICAO) REFERENCES TB_COND_PAGAMENTOS_TCC (ID)
);

CREATE TABLE TB_MOVCOMPRA_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL, 
    ID_CLIENTE INT NOT NULL,
    ID_FRMPAGAMENTO INT NOT NULL, 
    DT_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VL_TOTAL INT(10, 2) NOT NULL,
    VL_DESCONTO INT(10, 2) NOT NULL,
    VL_DESCONTO_PR INT(10, 2) NOT NULL,
    VL_LIQUIDO INT(10, 2) NOT NULL, 
    STATUS VARCHAR(20) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_MOVCOMPRA_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MOVCOMPRA_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID),
    CONSTRAINT FK_ID_CLIENTE_TB_MOVCOMPRA_TCC FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES_TCC (ID),    
    CONSTRAINT FK_ID_FRMPAGAMENTO_TB_MOVCOMPRA_TCC FOREIGN KEY (ID_FRMPAGAMENTO) REFERENCES TB_FRM_PAGAMENTOS_TCC (ID)
);

CREATE TABLE TB_MOVVENDA_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL, 
    ID_CLIENTE INT NOT NULL,
    ID_FRMPAGAMENTO INT NOT NULL, 
    DT_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VL_TOTAL INT(10, 2) NOT NULL,
    VL_DESCONTO INT(10, 2) NOT NULL,
    VL_DESCONTO_PR INT(10, 2) NOT NULL,
    VL_LIQUIDO INT(10, 2) NOT NULL, 
    STATUS VARCHAR(20) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_MOVVENDA_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MOVVENDA_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID),
    CONSTRAINT FK_ID_CLIENTE_TB_MOVVENDA_TCC FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES_TCC (ID),    
    CONSTRAINT FK_ID_FRMPAGAMENTO_TB_MOVVENDA_TCC FOREIGN KEY (ID_FRMPAGAMENTO) REFERENCES TB_FRM_PAGAMENTOS_TCC (ID)
);

CREATE TABLE TB_MOVCOMPRAITENS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    ID_MOVCOMPRA INT NOT NULL, 
	ID_CLIENTE INT NOT NULL,
    SEQUENCIA INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VL_UNITARIO INT(10, 2) NOT NULL,  
    VL_TOTAL INT(10, 2) NOT NULL,  
    DESCONTO INT(10, 2) NOT NULL, 
    PR_ACRESCIMO INT(10, 2) NOT NULL, 
    PR_DESCONTO INT(10, 2) NOT NULL, 
    VL_LIQUIDO INT(10, 2) NOT NULL, 
    DT_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_MOVCOMPRAITENS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MOVCOMPRAITENS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID),
    CONSTRAINT FK_ID_MOVCOMPRA_TB_MOVCOMPRAITENS_TCC FOREIGN KEY (ID_MOVCOMPRA) REFERENCES TB_MOVCOMPRA_TCC (ID),
    CONSTRAINT FK_ID_CLIENTE_TB_MOVCOMPRAITENS_TCC FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES_TCC (ID)
);

CREATE TABLE TB_MOVVENDAITENS_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
    ID_MOVVENDA INT NOT NULL, 
    SEQUENCIA INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VL_UNITARIO INT(10, 2) NOT NULL,  
    VL_TOTAL INT(10, 2) NOT NULL,  
    DESCONTO INT(10, 2) NOT NULL, 
    PR_ACRESCIMO INT(10, 2) NOT NULL, 
    PR_DESCONTO INT(10, 2) NOT NULL, 
    VL_LIQUIDO INT(10, 2) NOT NULL, 
    DT_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_MOVVENDAITENS_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MOVVENDAITENS_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID),
    CONSTRAINT FK_ID_MOVVENDA_TB_MOVVENDAITENS_TCC FOREIGN KEY (ID_MOVVENDA) REFERENCES TB_MOVVENDA_TCC (ID),
    CONSTRAINT FK_ID_CLIENTE_TB_MOVVENDAITENS_TCC FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES_TCC (ID)
);

CREATE TABLE TB_CAIXA_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    SALDO_INICIAL INT(10, 2) NOT NULL,
    SALDO_ATUAL INT(10, 2) NOT NULL,
    SALDO_FECHAMENTO INT(10, 2),
    DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_FECHAMENTO TIMESTAMP,
    STATUS VARCHAR(20) CHECK (STATUS IN ('Aberto', 'Fechado')) DEFAULT 'Aberto',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_CAIXA_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID)
);

CREATE TABLE TB_MOV_CAIXA_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CAIXA INT NOT NULL,
    ID_EMPRESA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
	ID_MOVIMENTO INT NOT NULL, -- TB CONTAS A RECEBER; PAGAR;
    TIPO_MOVIMENTACAO VARCHAR(20) CHECK (TIPO_MOVIMENTACAO IN ('Venda', 'Sangria', 'Suprimento', 'Pagamento', 'Recebimento')) NOT NULL,
    DESCRICAO VARCHAR(255),
    VALOR INT(10, 2) NOT NULL,
    DATA_MOVIMENTACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_CAIXA_TB_MOV_CAIXA_TCC FOREIGN KEY (ID_CAIXA) REFERENCES TB_CAIXA_TCC (ID),
    CONSTRAINT FK_ID_EMPRESA_TB_MOV_CAIXA_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_MOV_CAIXA_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID)
);

CREATE TABLE TB_CONTAS_PAGAR_TCC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,
	
	ID_MOVCOMPRA INT, -- FAZENDO MENÇÃO A COMPRA FEITA NO PEDIDO DE COMPRA COM FORNECEDOR
	
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR INT(10, 2) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_PAGAMENTO DATE,
    PARCELA VARCHAR(20) NOT NULL, -- Exemplo: '1/3' para indicar a primeira parcela de três
    STATUS VARCHAR(20) CHECK (STATUS IN ('Pendente', 'Pago', 'Atrasado')) DEFAULT 'Pendente',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ID_EMPRESA_TB_CONTAS_PAGAR_TCC FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESAS_TCC (ID),
    CONSTRAINT FK_ID_USUARIO_TB_CONTAS_PAGAR_TCC FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_TCC (ID),
    CONSTRAINT FK_ID_FORNECEDOR_TB_CONTAS_PAGAR_TCC FOREIGN KEY (ID_FORNECEDOR) REFERENCES TB_FORNECEDORES_TCC (ID)
);